### ISSUE TITLE
humans.txt text needs to be corrected

### ISSUE THREAD

**Issue by zhekovka** [Intecmedia/Intecmedia.Webpack#112]
Text:
By https://pitcher.agency. Making the digital world a better since 2001.
Hi there! Do you think, can you as well or better? Tell us about it: info@pitcher.agency.

Should be

By https://pitcher.agency. Making the digital world better since 2001.
Hi there! Do you think you can do the same or better? Tell us about it: info@pitcher.agency.

1. a better -- артикли ставятся только перед существительными, так что либо making the world better либо making the world a better place
2. Do you think, can you -- это сложноподчиненное предложение, you can do это придаточное и переносить can вперед там не нужно
3. As well употребляется в значении "тоже" и ставится в конец предложения, например I can do it as well = Я тоже могу сделать это
the same -- это "так же" I can do the same = Я могу сделать так же.

**Comment by dkrnl** [comment]
Thx!
https://github.com/Intecmedia/Intecmedia.Webpack/commit/6879825174a4ecda8f3f1833b74524a1b319b534
