### ISSUE TITLE
Замени intecmedia-banner.jpg на og-image, например

### ISSUE THREAD

**Issue by ekrovyakov** [Intecmedia/Intecmedia.Webpack#185]
https://github.com/Intecmedia/Intecmedia.Webpack/blob/master/source/upload/intecmedia-banner.jpg

Какие интекмедии вообще?
Он в wysiwyg.html используется.

**Comment by dkrnl** [comment]
это тестовая картинка, не больше чем просто тест -- которого не должно быть в продакшене

**Comment by dkrnl** [comment]
mmit/a8a376c0bfb879e7917f3adea62c4f941f9ac967
