### ISSUE TITLE
Заменить og-image

### ISSUE THREAD

**Issue by ekrovyakov** [Intecmedia/Intecmedia.Webpack#186]
https://github.com/Intecmedia/Intecmedia.Webpack/blob/master/source/img/og-image.png

На эту:
![og-image](https://github.com/Intecmedia/Intecmedia.Webpack/assets/81800249/90b1c120-c44a-4ed4-b8b7-3ba4dc55b84c)

**Comment by dkrnl** [comment]
https://github.com/Intecmedia/Intecmedia.Webpack/commit/7a61fa12d98145c65f966519755686e166d09775
