### ISSUE TITLE
Разные конфигурации линтеров

### ISSUE THREAD

**Issue by radist** [Intecmedia/Intecmedia.Webpack#21]
npm run lint  и npm run production используют разные конигурации линтеров? 

При запуске npm run production находит то, чего не было при npm run lint

**Comment by dkrnl** [comment]
да, разные. т.к не все stylelint-палины поддерживают scss: 
например stylelint-csstree-validator может проверять только css
также сложный scss синтаксис может скрывать неочевидные ошибки.

**Comment by radist** [comment]
no-low-performance-animation есть только в production. Хотя вроде нормально работают и в npm run lint если добавить в конфиг
