### ISSUE TITLE
Назначение npm run watch-* и npm run server-*

### ISSUE THREAD

**Issue by radist** [Intecmedia/Intecmedia.Webpack#22]
При запуске npm run watch-* вижу следующую картину. Что то на так сделано\настроено? или каково назначение данной команды?

![image](https://user-images.githubusercontent.com/106756/89302856-12e88480-d674-11ea-9d98-414d99fd4c9f.png)

В чем отличие команд npm run watch-* и npm run server-* ?

**Comment by dkrnl** [comment]
[Watch mode](https://webpack.js.org/configuration/watch/) **не** запускает встроенный в вебпак дев-сервер. То что на фото -- не знаю, это ваш вебсервер.

Watch только смотрит за изменениями source директории и складывает их в директорию build. Нужен для интеграции со сторонними CMS.

npm run server - запускается встроенный [webpack-dev-server](https://webpack.js.org/configuration/dev-server/) в оперативной памяти (без файловой системы и записи в build)
